"""empty message

Revision ID: 122c656bbff7
Revises: d7cb6e94685c
Create Date: 2021-01-04 14:09:45.535707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122c656bbff7'
down_revision = 'd7cb6e94685c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('meter', sa.Float(), nullable=False),
    sa.Column('inverter', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy')
    # ### end Alembic commands ###
