"""empty message

Revision ID: 9d0f77e61993
Revises: 122c656bbff7
Create Date: 2021-01-11 14:48:00.382836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d0f77e61993'
down_revision = '122c656bbff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy', sa.Column('energy', sa.Float(), nullable=False))
    op.drop_column('energy', 'inverter')
    op.drop_column('energy', 'meter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy', sa.Column('meter', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('energy', sa.Column('inverter', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('energy', 'energy')
    # ### end Alembic commands ###
